<?php

/**
 * Anime Tracker - Setup Wizard
 * https://www.sicakcikolata.com
 * Copyright (C) 2025 Okan Sumer
 * Licensed under GNU General Public License v2
 *
 * WordPress-style first-time setup. The user lands here automatically
 * (via db.php redirect) when config.php is missing. Collects database
 * credentials through a form, creates config.php using var_export()
 * for safe value serialisation, then redirects to install.php which
 * will load the schema.
 *
 * Safe-value serialisation matters: if the user picks a password
 * containing quotes or backslashes, naive string concatenation would
 * break PHP syntax or - worse - allow code injection through the
 * password field. var_export() handles all escaping correctly.
 *
 * This file should be deleted after successful installation. The
 * install.php success page reminds the user. The .exe installer
 * deletes both files automatically (installer.nsi lines 169-170).
 *
 * No CSRF token: setup is the very first page a user sees, before
 * any session has been established. A first-run attack surface is
 * negligible (the attacker would need local web access before any
 * credentials exist).
 */

// If config.php already exists, setup has been run. Send the user
// either to install.php (if DB tables are not yet created) or back
// to the main page. We can't easily tell which one applies without
// a DB connection, so we send them to install.php which is idempotent.
if (file_exists(__DIR__ . '/config.php')) {
    header('Location: install.php');
    exit;
}

$errors = [];
$defaults = [
    'db_host' => 'localhost',
    'db_name' => 'anime_tracker',
    'db_user' => 'root',
    'db_pass' => '',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Collect form values, falling back to defaults for missing fields.
    $host = trim($_POST['db_host'] ?? '');
    $name = trim($_POST['db_name'] ?? '');
    $user = trim($_POST['db_user'] ?? '');
    $pass = $_POST['db_pass'] ?? ''; // Don't trim password - user might want leading/trailing spaces

    // Minimal validation. The DB driver will catch the rest.
    if ($host === '') { $errors[] = 'Veritabani sunucu adi bos birakilamaz.'; }
    if ($name === '') { $errors[] = 'Veritabani adi bos birakilamaz.'; }
    if ($user === '') { $errors[] = 'Veritabani kullanici adi bos birakilamaz.'; }

    // Keep submitted values so the form can re-render them on error
    $defaults = [
        'db_host' => $host,
        'db_name' => $name,
        'db_user' => $user,
        'db_pass' => $pass,
    ];

    if (empty($errors)) {
        // Step 1: Try connecting to the server (without selecting a DB).
        // This lets us create the database if it doesn't exist yet.
        try {
            $pdo = new PDO(
                'mysql:host=' . $host . ';charset=utf8mb4',
                $user,
                $pass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );

            // Step 2: Create the database if it doesn't exist.
            // Backticks around the name handle unusual characters, but
            // we still validate the name as a precaution. DB names can
            // contain letters, digits, underscores, dollar signs.
            if (!preg_match('/^[A-Za-z0-9_$]+$/', $name)) {
                throw new Exception('Veritabani adi gecersiz karakterler iceriyor. Sadece harf, rakam, alt cizgi ve dolar isareti kullanin.');
            }
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci");

            // Step 3: Re-connect with the database selected, to verify
            // that the user has access to it.
            new PDO(
                'mysql:host=' . $host . ';dbname=' . $name . ';charset=utf8mb4',
                $user,
                $pass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );

            // Step 4: Write config.php using var_export for safe serialisation.
            // var_export produces PHP source code that, when eval'd, reproduces
            // the exact value - handles quotes, backslashes, null bytes, etc.
            $lines = [
                '<?php',
                '',
                '// Generated by setup.php on ' . date('Y-m-d H:i:s'),
                '// Server-side defaults use UTC for all date calculations.',
                "date_default_timezone_set('UTC');",
                '',
                'define(' . var_export('DB_HOST', true) . ', ' . var_export($host, true) . ');',
                'define(' . var_export('DB_NAME', true) . ', ' . var_export($name, true) . ');',
                'define(' . var_export('DB_USER', true) . ', ' . var_export($user, true) . ');',
                'define(' . var_export('DB_PASS', true) . ', ' . var_export($pass, true) . ');',
                '',
            ];
            $contents = implode("\n", $lines);

            $bytesWritten = @file_put_contents(__DIR__ . '/config.php', $contents);
            if ($bytesWritten === false) {
                throw new Exception(
                    'config.php olusturulamadi. Bu klasore yazma izni yok. ' .
                    'Web sunucusuna bu dizin icin yazma yetkisi verin veya ' .
                    'config.php dosyasini elle olusturun.'
                );
            }

            // Success - redirect to install.php to load the schema.
            header('Location: install.php');
            exit;

        } catch (PDOException $e) {
            $errors[] = 'Veritabani baglantisi basarisiz: ' . $e->getMessage();
        } catch (Exception $e) {
            $errors[] = $e->getMessage();
        }
    }
}

?>
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <title>Anime Tracker - Kurulum</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <style>
        .setup-container {
            max-width: 600px;
            margin: 40px auto;
            padding: 30px;
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .setup-container h1 {
            margin-top: 0;
            color: #333;
        }
        .setup-container .intro {
            color: #666;
            margin-bottom: 25px;
            line-height: 1.5;
        }
        .form-row {
            margin-bottom: 15px;
        }
        .form-row label {
            display: block;
            font-weight: 500;
            margin-bottom: 5px;
            color: #333;
        }
        .form-row input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
            box-sizing: border-box;
        }
        .form-row small {
            color: #888;
            font-size: 12px;
            display: block;
            margin-top: 4px;
        }
        .submit-button {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 12px 25px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 15px;
            font-weight: 500;
        }
        .submit-button:hover {
            background-color: #0056b3;
        }
        .errors {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .errors ul {
            margin: 0;
            padding-left: 20px;
        }
    </style>
</head>
<body>
    <div class="setup-container">
        <h1><i class="fas fa-cog"></i> Anime Tracker Kurulum</h1>
        <p class="intro">
            Hos geldiniz! Bu sihirbaz veritabani baglantisini kurmaniza yardimci olacak.
            Kurulum tamamlandiktan sonra uygulamayi kullanmaya baslayabilirsiniz.
        </p>

        <?php if (!empty($errors)): ?>
            <div class="errors">
                <strong>Kurulum sirasinda bir sorun olustu:</strong>
                <ul>
                    <?php foreach ($errors as $err): ?>
                        <li><?php echo htmlspecialchars($err, ENT_QUOTES, 'UTF-8'); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form method="post">
            <div class="form-row">
                <label for="db_host">Veritabani Sunucusu</label>
                <input type="text" id="db_host" name="db_host" value="<?php echo htmlspecialchars($defaults['db_host'], ENT_QUOTES, 'UTF-8'); ?>" required>
                <small>Yerel XAMPP/WAMP kurulumlarinda genellikle "localhost"tur.</small>
            </div>

            <div class="form-row">
                <label for="db_name">Veritabani Adi</label>
                <input type="text" id="db_name" name="db_name" value="<?php echo htmlspecialchars($defaults['db_name'], ENT_QUOTES, 'UTF-8'); ?>" required>
                <small>Veritabani yoksa otomatik olusturulacaktir.</small>
            </div>

            <div class="form-row">
                <label for="db_user">Veritabani Kullanici Adi</label>
                <input type="text" id="db_user" name="db_user" value="<?php echo htmlspecialchars($defaults['db_user'], ENT_QUOTES, 'UTF-8'); ?>" required>
                <small>XAMPP'ta genellikle "root"tur.</small>
            </div>

            <div class="form-row">
                <label for="db_pass">Veritabani Sifresi</label>
                <input type="password" id="db_pass" name="db_pass" value="<?php echo htmlspecialchars($defaults['db_pass'], ENT_QUOTES, 'UTF-8'); ?>">
                <small>XAMPP varsayilan kurulumunda bos birakilir.</small>
            </div>

            <button type="submit" class="submit-button">
                <i class="fas fa-check"></i> Kurulumu Baslat
            </button>
        </form>
    </div>
</body>
</html>
