<?php
/**
 * Anime Tracker - Install counter ("install ping")
 * https://www.sicakcikolata.com
 * Copyright (C) 2025-2026 Okan Sumer
 * Licensed under GNU General Public License v2
 *
 * Introduced in 1.1.43.
 *
 * WHY THIS FILE EXISTS
 *
 * The project is open source and self-hostable, so nobody knows how many
 * installations exist: a self-host copy never has to talk to the central
 * catalog, and the update check only fires when its button is pressed.
 * This helper gives the project a plain COUNT - "how many installs are
 * out there, and on which version they started" - and nothing more.
 *
 * WHAT IS SENT, AND WHAT IS NOT
 *
 * ONCE per installation, one GET request to INSTALL_PING_URL with three
 * values:
 *
 *   id  - a random 32-hex token generated on this install the first time
 *         the ping runs (settings.install_id). It is not derived from the
 *         site address, the database, the owner, or anything else; it only
 *         lets the counter ignore a duplicate (a retry, a restored backup).
 *         Deleting the settings row makes this install count as a new one.
 *   v   - the installed code version (files/version.txt).
 *   m   - 'single' (self-host) or 'multi' (online / members site).
 *
 * NOT sent: the site address, the user count, any anime, any personal data,
 * the server's hostname or software. The receiving endpoint stores the
 * three values plus a first-seen timestamp; it does not store the IP.
 *
 * Decided 19 Sep 2026: one ping per install, not one per day. A daily
 * heartbeat would also answer "how many are still alive", but the owner
 * chose the smallest possible footprint - "if we ever need more, we
 * extend it". The gate below is built so that extension is one line.
 *
 * TURNING IT OFF
 *
 *   define('INSTALL_PING', false);   // in config.php
 *
 * A missing constant means enabled (the same "older config.php files keep
 * working" convention MULTI_USER_MODE uses in db.php). Fresh installs get
 * the line written into config.php by setup.php so the switch is visible.
 *
 * HOW IT IS TRIGGERED
 *
 * Not from the page render. index.php only checks install_ping_due() and,
 * when the ping has not succeeded yet, prints a one-line fetch() to the
 * local install_ping.php endpoint. That endpoint does the outbound request
 * with a short timeout, so a slow or dead counter server can never slow a
 * page the user is looking at (the same reason check_update.php sits
 * behind a fetch instead of inline in list_settings.php).
 *
 * RETRY: at most ONE attempt per UTC day until the first success, then
 * never again. install_ping_send() records the attempt day BEFORE it
 * sends, and records the success (settings.install_ping_done) only on
 * HTTP 200. So an install set up while the counter is down is still
 * counted - tomorrow - without hammering anything meanwhile.
 */

// Where the one-time ping goes and where the admin card reads the public
// numbers from (?stats=1). A fork that wants its own counter changes this
// one line and deploys catalog_server/ping.php on its own host.
const INSTALL_PING_URL = 'https://animetracker.sicakcikolata.com/ping.php';

/**
 * Is the install ping switched on for this installation?
 *
 * Absent constant = on (see the file docblock). Only an explicit
 * define('INSTALL_PING', false) turns it off.
 *
 * @return bool
 */
function install_ping_enabled()
{
    return !defined('INSTALL_PING') || (bool)INSTALL_PING;
}

/**
 * Should index.php ask the browser to trigger the ping?
 *
 * True when the ping is enabled, has never succeeded
 * (settings.install_ping_done missing) and has not been attempted today
 * (settings.last_install_ping != today's UTC date). Any DB error means
 * "not due": a counter must never surface an error to the user.
 *
 * @param PDO $pdo
 * @return bool
 */
function install_ping_due(PDO $pdo)
{
    if (!install_ping_enabled()) {
        return false;
    }
    try {
        $stmt = $pdo->query(
            "SELECT name, value FROM settings
              WHERE name IN ('install_ping_done', 'last_install_ping')"
        );
        $rows = $stmt->fetchAll(PDO::FETCH_KEY_PAIR);
    } catch (PDOException $e) {
        return false;
    }
    if (!empty($rows['install_ping_done'])) {
        return false;
    }
    return ((string)($rows['last_install_ping'] ?? '')) !== gmdate('Y-m-d');
}

/**
 * Return this install's random id, creating it on first use.
 *
 * 32 lowercase hex characters from random_bytes(16). Stored in
 * settings.install_id. Never regenerated by the application; deleting the
 * row is the only way to get a new one (and makes this install count as a
 * new install on the counter).
 *
 * @param PDO $pdo
 * @return string|null  null when the settings table cannot be read/written
 */
function install_id_get_or_create(PDO $pdo)
{
    try {
        $stmt = $pdo->query("SELECT value FROM settings WHERE name = 'install_id'");
        $id = $stmt->fetchColumn();
        if (is_string($id) && preg_match('/^[0-9a-f]{32}$/', $id)) {
            return $id;
        }
        $id = bin2hex(random_bytes(16));
        // INSERT ... ON DUPLICATE KEY UPDATE, the settings-table convention.
        // The UPDATE branch only matters if two first-ever pings race: the
        // second one overwrites the first id, harmless (one extra "install"
        // for a day, then both rows converge on the surviving id).
        $ins = $pdo->prepare(
            "INSERT INTO settings (name, value) VALUES ('install_id', ?)
             ON DUPLICATE KEY UPDATE value = VALUES(value)"
        );
        $ins->execute([$id]);
        return $id;
    } catch (Exception $e) {
        error_log('[anime_tracker] install_id could not be created: ' . $e->getMessage());
        return null;
    }
}

/**
 * Record today's attempt, send the ping, and on success mark it done.
 *
 * Called only by install_ping.php. Re-checks install_ping_due() so a
 * second request on the same day (two tabs opened together, a crawler
 * running the page's JS) does nothing.
 *
 * @param PDO $pdo
 * @return array  ['sent' => bool, 'http' => int, 'skipped' => string|null]
 */
function install_ping_send(PDO $pdo)
{
    if (!install_ping_due($pdo)) {
        return ['sent' => false, 'http' => 0, 'skipped' => 'not_due'];
    }

    $id = install_id_get_or_create($pdo);
    if ($id === null) {
        return ['sent' => false, 'http' => 0, 'skipped' => 'no_install_id'];
    }

    // Mark the attempt day FIRST - one attempt per UTC day, success or not.
    try {
        $mark = $pdo->prepare(
            "INSERT INTO settings (name, value) VALUES ('last_install_ping', ?)
             ON DUPLICATE KEY UPDATE value = VALUES(value)"
        );
        $mark->execute([gmdate('Y-m-d')]);
    } catch (PDOException $e) {
        error_log('[anime_tracker] last_install_ping could not be written: ' . $e->getMessage());
        return ['sent' => false, 'http' => 0, 'skipped' => 'mark_failed'];
    }

    $version = function_exists('asset_version') ? asset_version() : '';
    $mode    = (defined('MULTI_USER_MODE') && MULTI_USER_MODE) ? 'multi' : 'single';

    $url = INSTALL_PING_URL . '?' . http_build_query([
        'id' => $id,
        'v'  => $version,
        'm'  => $mode,
    ]);

    // Same transport as check_update.php: stream context with a short
    // timeout and ignore_errors so a 4xx/5xx still yields a status code.
    // 3 seconds is generous for a request whose body is a few bytes; the
    // user is not waiting on it either way (see the file docblock).
    $context = stream_context_create([
        'http' => [
            'method'        => 'GET',
            'timeout'       => 3,
            'ignore_errors' => true,
            'header'        => 'User-Agent: AnimeTracker/' . ($version !== '' ? $version : 'unknown')
                             . ' (install-ping)' . "\r\n",
        ],
    ]);

    $body = @file_get_contents($url, false, $context);

    $status = 0;
    if (isset($http_response_header[0])
        && preg_match('#^HTTP/\S+\s+(\d+)#', $http_response_header[0], $m)) {
        $status = (int)$m[1];
    }

    if ($body === false || $status !== 200) {
        // Logged, not surfaced. Tomorrow's page load tries again.
        error_log('[anime_tracker] install ping failed: HTTP ' . $status);
        return ['sent' => false, 'http' => $status, 'skipped' => null];
    }

    // Success: never again for this install. If this write fails the only
    // consequence is one more ping tomorrow, which the server ignores as a
    // duplicate id.
    try {
        $done = $pdo->prepare(
            "INSERT INTO settings (name, value) VALUES ('install_ping_done', ?)
             ON DUPLICATE KEY UPDATE value = VALUES(value)"
        );
        $done->execute([gmdate('Y-m-d H:i:s')]);
    } catch (PDOException $e) {
        error_log('[anime_tracker] install_ping_done could not be written: ' . $e->getMessage());
    }

    return ['sent' => true, 'http' => 200, 'skipped' => null];
}
