-- Anime Tracker - Migration 1.1.2
-- https://www.sicakcikolata.com
-- Copyright (C) 2025 Okan Sumer
-- Licensed under GNU General Public License v2
--
-- Adds the adult-content flag to the catalog (animes.is_adult).
--
-- is_adult is catalog-level metadata (like media_type): a value of 1
-- marks an anime as 18+/adult. Rows default to 0 (not adult). The flag
-- is written from the add/edit forms and travels with the catalog
-- push/import wire format so it stays consistent across installs.
--
-- Viewer visibility is a SEPARATE, schema-free concern: the per-user
-- 'show_adult_content' preference lives in user_pref (runtime key, same
-- family as display_language / display_title_english), so no column is
-- added for it here. Default-off hiding is enforced in the query layer.
--
-- Idempotency: this is a real ALTER. If the column already exists the
-- runner swallows error 1060 (duplicate column) - see
-- migration_manager.php isIdempotentError() - so a partial or repeated
-- run is safe and simply advances settings.version to 1.1.2.

ALTER TABLE `animes` ADD COLUMN `is_adult` TINYINT(1) NOT NULL DEFAULT 0;
