-- Anime Tracker - Migration 1.2.2
-- https://www.sicakcikolata.com
-- Copyright (C) 2025-2026 Okan Sumer
-- Licensed under GNU General Public License v2
--
-- =====================================================================
-- 1.2.2 - SEMA DEGISIKLIGI YOKTUR
-- =====================================================================
--
-- Bu dosya bilerek BOSTUR. Runner yorumlari temizler, calistiracak ifade
-- bulamaz ve yalnizca settings.version'i 1.2.2'ye tasir. Klasorun var
-- olmasi gerekiyor: surum atlanirsa MigrationManager sirayi kaybeder.
-- (Ayni kalip 1.2.0 / 1.2.1'de kullanildi.)
--
-- ---------------------------------------------------------------------
-- Bu surumde ne var: seri kronolojisinde sayfa ici sekmeler
-- ---------------------------------------------------------------------
--
-- series_timeline.php liste sekmelerini (kendi hatti, diger hatlar,
-- Yayin Tarihi) tek sayfada cizer; js/series_tabs.js yeniden yuklemeden
-- degistirir. IndexNow: serinin herhangi bir uyesi degisince bas kaydin
-- seri adresi de duyurulur (seo_anime_locs). Hepsi kod; veri yazilmaz.
--
-- Yeni tablo / kolon / indeks YOK.
--
-- MERKEZ KATALOG: is YOK.
-- =====================================================================
