-- Anime Tracker - Migration 0.7.7
-- https://www.sicakcikolata.com
-- Copyright (C) 2025-2026 Okan Sumer
-- Licensed under GNU General Public License v2
--
-- Anime Tracker 0.7.7 migration
-- No schema change. Version bump only.
--
-- The tags.name_en and genres.name_en columns this release uses for
-- catalog sync already exist (added in 0.7.2). This empty migration
-- only advances settings.version so installations that skip straight
-- to 0.7.7 do not stay pinned at an earlier version.
