-- Anime Tracker 0.6.4 migration
-- No schema changes in this release.
-- This file exists only to bump settings.version to 0.6.4.
-- The actual fix is the add_genre.php CSRF protection
-- (PHP-only change, no DB impact).
-- captain future anime finish. i plan today(27.05.2026) continue Mairimashita! Iruma-kun.