#!/bin/bash
# Anime Tracker - Docker Entrypoint
#
# Bu script her container basladiginda calisir. Iki gorevi var:
#   1. config.php yoksa ortam degiskenlerinden olusturur (ilk calistirmada)
#   2. Yazilabilir klasorlerin (uploads, temp) izinlerini ayarlar
#
# Schema yukleme bu scriptin isi degildir. MariaDB'nin kendi
# docker-entrypoint-initdb.d mekanizmasi files/schema.sql'i otomatik
# yukluyor (docker-compose.yml icinde mount ediliyor).
#
# NOT: Bu dosya Unix (LF) satir sonlari ile kaydedilmelidir. Windows
# editorlerinde CRLF kaydederseniz bash "bad interpreter" hatasi verir.
# Dockerfile, build sirasinda dos2unix calistirarak bu durumu otomatik
# olarak duzeltir - ama yine de LF olarak tutmak iyi uygulamadir.

set -e

# config.php yoksa olustur. Container ilk kez calisiyor demektir.
# Sonraki baslatmalarda bu dosya zaten var, atlanir.
if [ ! -f /var/www/html/config.php ]; then
    echo "[anime_tracker] config.php bulunamadi, olusturuluyor..."

    # Ortam degiskenleri docker-compose.yml'den geliyor. Varsayilan
    # degerler Docker Hub image'i kullanicilari icin makul:
    #   DB_HOST=db (compose network'te servis adi)
    #   DB_NAME=anime_tracker
    #   DB_USER=root
    #   DB_PASS=root
    # Production kullanimi icin .env ile override edilmelidir.
    cat > /var/www/html/config.php <<PHPEOF
<?php
// Generated by docker-entrypoint.sh on container start.
// Values come from environment variables set in docker-compose.yml.
date_default_timezone_set('UTC');

define('DB_HOST', '${DB_HOST:-db}');
define('DB_NAME', '${DB_NAME:-anime_tracker}');
define('DB_USER', '${DB_USER:-root}');
define('DB_PASS', '${DB_PASS:-root}');
PHPEOF

    chown www-data:www-data /var/www/html/config.php
    chmod 640 /var/www/html/config.php

    echo "[anime_tracker] config.php olusturuldu."
fi

# uploads klasoru: kapak gorselleri buraya yazilir.
# Volume olarak mount ediliyor, ama izinleri her basta yeniden ayarla
# (host'tan mount edildiginde owner farkli olabilir).
mkdir -p /var/www/html/uploads
chown -R www-data:www-data /var/www/html/uploads

# temp klasoru: update.php indirme/extract icin kullaniyor.
# Volume degil cunku gecici veri, container yasam dongusune bagli olabilir.
mkdir -p /var/www/html/temp
chown -R www-data:www-data /var/www/html/temp

# migration klasoru (varsa): migration_manager.php'nin okumasi gerekiyor.
# Container image'ina gomulu geldigi icin sahiplik www-data olmali.
if [ -d /var/www/html/migration ]; then
    chown -R www-data:www-data /var/www/html/migration
fi

# Orijinal PHP + Apache entrypoint'ine devam et.
# docker-php-entrypoint, CMD olarak verilen apache2-foreground'u calistirir.
exec docker-php-entrypoint "$@"
