-- Anime Tracker - Migration 1.0.9
-- https://www.sicakcikolata.com
-- Copyright (C) 2025-2026 Okan Sumer
-- Licensed under GNU General Public License v2
--
-- =====================================================================
-- 1.0.9 - empty ring (no-op)
-- =====================================================================
-- 
