-- Anime Tracker - Migration 0.5.2
-- https://www.sicakcikolata.com
-- Copyright (C) 2025-2026 Okan Sumer
-- Licensed under GNU General Public License v2
--
-- Anime Tracker 0.5.1 migration
-- No schema changes in this release.
-- This file exists only to bump settings.version to 0.5.1.
-- The actual fix is the add_genre.php CSRF protection
-- (PHP-only change, no DB impact).