<?php

/**
 * Anime Tracker - Setup Wizard (English)
 * https://www.sicakcikolata.com
 * Copyright (C) 2025 Okan Sumer
 * Licensed under GNU General Public License v2
 *
 * English twin of setup.php. Setup and install run before the database
 * exists, so the lang_init/t() dictionary system cannot be used here.
 * Following the ai_notice.php / ai_notice_en.php convention, the English
 * setup screen is a separate static file reached through the language
 * link on setup.php.
 *
 * Behaviour mirrors setup.php exactly, with one difference: this file
 * keeps the user inside the English flow by redirecting to install_en.php
 * (not install.php) after config.php is written.
 *
 * Safe-value serialisation matters: if the user picks a password
 * containing quotes or backslashes, naive string concatenation would
 * break PHP syntax or - worse - allow code injection through the
 * password field. var_export() handles all escaping correctly.
 *
 * This file should be deleted after successful installation. The
 * install_en.php success page reminds the user. The .exe installer
 * deletes the setup files automatically (installer.nsi lines 169-170).
 *
 * No CSRF token: setup is the very first page a user sees, before
 * any session has been established. A first-run attack surface is
 * negligible (the attacker would need local web access before any
 * credentials exist).
 */

// If config.php already exists, setup has been run. Send the user
// to install_en.php (idempotent) to stay inside the English flow.
if (file_exists(__DIR__ . '/config.php')) {
    header('Location: install_en.php');
    exit;
}

$errors = [];
$defaults = [
    'db_host'      => 'localhost',
    'db_name'      => 'anime_tracker',
    'db_user'      => 'root',
    'db_pass'      => '',
    'install_type' => 'single',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Collect form values, falling back to defaults for missing fields.
    $host = trim($_POST['db_host'] ?? '');
    $name = trim($_POST['db_name'] ?? '');
    $user = trim($_POST['db_user'] ?? '');
    $pass = $_POST['db_pass'] ?? ''; // Don't trim password - user might want leading/trailing spaces

    // Installation type: 'single' (self-host, no login) or 'multi' (online,
    // login required). Anything other than 'multi' is treated as 'single'.
    $install_type = (($_POST['install_type'] ?? 'single') === 'multi') ? 'multi' : 'single';

    // Minimal validation. The DB driver will catch the rest.
    if ($host === '') { $errors[] = 'Database server name cannot be empty.'; }
    if ($name === '') { $errors[] = 'Database name cannot be empty.'; }
    if ($user === '') { $errors[] = 'Database username cannot be empty.'; }

    // Keep submitted values so the form can re-render them on error
    $defaults = [
        'db_host'      => $host,
        'db_name'      => $name,
        'db_user'      => $user,
        'db_pass'      => $pass,
        'install_type' => $install_type,
    ];

    if (empty($errors)) {
        // Step 1: Try connecting to the server (without selecting a DB).
        // This lets us create the database if it doesn't exist yet.
        try {
            $pdo = new PDO(
                'mysql:host=' . $host . ';charset=utf8mb4',
                $user,
                $pass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );

            // Step 2: Create the database if it doesn't exist.
            // Backticks around the name handle unusual characters, but
            // we still validate the name as a precaution. DB names can
            // contain letters, digits, underscores, dollar signs.
            if (!preg_match('/^[A-Za-z0-9_$]+$/', $name)) {
                throw new Exception('Database name contains invalid characters. Use only letters, digits, underscores and dollar signs.');
            }
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci");

            // Step 3: Re-connect with the database selected, to verify
            // that the user has access to it.
            new PDO(
                'mysql:host=' . $host . ';dbname=' . $name . ';charset=utf8mb4',
                $user,
                $pass,
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );

            // Step 4: Write config.php using var_export for safe serialisation.
            // var_export produces PHP source code that, when eval'd, reproduces
            // the exact value - handles quotes, backslashes, null bytes, etc.
            $lines = [
                '<?php',
                '',
                '// Generated by setup_en.php on ' . date('Y-m-d H:i:s'),
                '// Server-side defaults use UTC for all date calculations.',
                "date_default_timezone_set('UTC');",
                '',
                'define(' . var_export('DB_HOST', true) . ', ' . var_export($host, true) . ');',
                'define(' . var_export('DB_NAME', true) . ', ' . var_export($name, true) . ');',
                'define(' . var_export('DB_USER', true) . ', ' . var_export($user, true) . ');',
                'define(' . var_export('DB_PASS', true) . ', ' . var_export($pass, true) . ');',
                '',
                '// Multi-user mode. false = single-user / self-host (no login);',
                '// true = online / multi-user (login required). Chosen at setup.',
                'define(' . var_export('MULTI_USER_MODE', true) . ', ' . var_export($install_type === 'multi', true) . ');',
                '',
            ];
            $contents = implode("\n", $lines);

            $bytesWritten = @file_put_contents(__DIR__ . '/config.php', $contents);
            if ($bytesWritten === false) {
                throw new Exception(
                    'config.php could not be created. This folder is not writable. ' .
                    'Grant the web server write permission for this directory, or ' .
                    'create config.php manually.'
                );
            }

            // Success - redirect to install_en.php to load the schema.
            header('Location: install_en.php');
            exit;

        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        } catch (Exception $e) {
            $errors[] = $e->getMessage();
        }
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Anime Tracker - Setup</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <style>
        .setup-container {
            max-width: 600px;
            margin: 40px auto;
            padding: 30px;
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .setup-container h1 {
            margin-top: 0;
            color: #333;
        }
        .setup-container .intro {
            color: #666;
            margin-bottom: 25px;
            line-height: 1.5;
        }
        .setup-container .lang-switch {
            text-align: right;
            margin-bottom: 10px;
            font-size: 0.9em;
        }
        .setup-container .lang-switch a {
            color: #007bff;
            text-decoration: none;
        }
        .setup-container .lang-switch a:hover {
            text-decoration: underline;
        }
        .form-row {
            margin-bottom: 15px;
        }
        .form-row label {
            display: block;
            font-weight: 500;
            margin-bottom: 5px;
            color: #333;
        }
        .form-row input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
            box-sizing: border-box;
        }
        .form-row select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
            box-sizing: border-box;
            background: #fff;
        }
        .form-row small {
            color: #888;
            font-size: 12px;
            display: block;
            margin-top: 4px;
        }
        .submit-button {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 12px 25px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 15px;
            font-weight: 500;
        }
        .submit-button:hover {
            background-color: #0056b3;
        }
        .errors {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
            padding: 15px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .errors ul {
            margin: 0;
            padding-left: 20px;
        }
    </style>
</head>
<body>
    <div class="setup-container">
        <div class="lang-switch">
            <a href="setup.php"><i class="fas fa-globe"></i> Türkçe</a>
        </div>

        <h1><i class="fas fa-cog"></i> Anime Tracker Setup</h1>
        <p class="intro">
            Welcome! This wizard will help you set up the database connection.
            Once setup is complete, you can start using the application.
        </p>

        <?php if (!empty($errors)): ?>
            <div class="errors">
                <strong>A problem occurred during setup:</strong>
                <ul>
                    <?php foreach ($errors as $err): ?>
                        <li><?php echo htmlspecialchars($err, ENT_QUOTES, 'UTF-8'); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form method="post">
            <div class="form-row">
                <label for="db_host">Database Server</label>
                <input type="text" id="db_host" name="db_host" value="<?php echo htmlspecialchars($defaults['db_host'], ENT_QUOTES, 'UTF-8'); ?>" required>
                <small>Usually "localhost" for local XAMPP/WAMP installs.</small>
            </div>

            <div class="form-row">
                <label for="db_name">Database Name</label>
                <input type="text" id="db_name" name="db_name" value="<?php echo htmlspecialchars($defaults['db_name'], ENT_QUOTES, 'UTF-8'); ?>" required>
                <small>It will be created automatically if it does not exist.</small>
            </div>

            <div class="form-row">
                <label for="db_user">Database Username</label>
                <input type="text" id="db_user" name="db_user" value="<?php echo htmlspecialchars($defaults['db_user'], ENT_QUOTES, 'UTF-8'); ?>" required>
                <small>Usually "root" on XAMPP.</small>
            </div>

            <div class="form-row">
                <label for="db_pass">Database Password</label>
                <input type="password" id="db_pass" name="db_pass" value="<?php echo htmlspecialchars($defaults['db_pass'], ENT_QUOTES, 'UTF-8'); ?>">
                <small>Left blank in a default XAMPP install.</small>
            </div>

            <div class="form-row">
                <label for="install_type">Installation Type</label>
                <select id="install_type" name="install_type">
                    <option value="single"<?php echo ($defaults['install_type'] === 'single') ? ' selected' : ''; ?>>Single-user (personal / this computer)</option>
                    <option value="multi"<?php echo ($defaults['install_type'] === 'multi') ? ' selected' : ''; ?>>Multi-user (online server)</option>
                </select>
                <small>Single-user: no login, the app works as it always has. Multi-user: login is required and you create an administrator account in the next step.</small>
            </div>

            <button type="submit" class="submit-button">
                <i class="fas fa-check"></i> Start Setup
            </button>
        </form>
    </div>
</body>
</html>
