-- Anime Tracker - Migration 1.0.8
-- https://www.sicakcikolata.com
-- Copyright (C) 2025-2026 Okan Sumer
-- Licensed under GNU General Public License v2
--
-- =====================================================================
-- Anime Tracker 1.0.8 - migration (no-op / bos halka)
-- =====================================================================
-- Angel Densetsu add list