-- Anime Tracker - Migration 0.7.6
-- https://www.sicakcikolata.com
-- Copyright (C) 2025-2026 Okan Sumer
-- Licensed under GNU General Public License v2
--
-- Anime Tracker 0.7.6 migration
-- No schema change. Version bump only.
--Snowball Earth very boring
